### PR TITLE
updated grammer

### PR DESCRIPTION
**Pull request by saswat94**

### CODE REVIEW

**Comment by waywardmonkeys** [comment]
This change is incorrect.

**Comment by saswat94** [comment]
Hallo Dylan lang.i want to tell you that I am 
New to git hub so I am just practicing how to
Make a pull request so please ignore it

**Comment by housel** [comment]
> Hallo Dylan lang.i want to tell you that I am
> New to git hub so I am just practicing how to
> Make a pull request so please ignore it

Sorry but your practicing is creating a burden on others.

**Comment by saswat94** [comment]
Ok I will take care of it

**Pull request closed without merging**
