### PR TITLE
Fix layout when page width changes

### LINKED ISSUE #96: Left nav overlaps main content
Moving this here from https://github.com/dylan-lang/opendylan/issues/1289.  May be related to https://github.com/dylan-lang/website/issues/51 but I can't quite tell.

The History web page at normal 0% magnification has the left nav overlapping the main text:
overlapping

When I use Ctrl-+ four times it seems to switch to some other mode (mobile?) and the overlapping goes away:
non-overlapping

Notes from @pedro-w:

(should be on the https://github.com/dylan-lang/website project I suppose)
I see the website is using css from 'bootstrap-responsive' and the media queries change the style at the following widths
* below 480px - a 'phone-like' style
* up to 768px - left nav on top (OK)
* up to 980px - left nav on left (OK)
* above this - left nav overlaps (not OK)

I can look at this in a more detail to figure it out. Note the css file is quite old (bootstrap 2.3.1 is from 2013) 

Based on modifying styles 'by hand' in the Developer tools, I think the navigation elements need to be in a div of class `row-fluid` rather than `row`. The source of this is in `source/history/index.rst`, line 3.
There may well be other instances of this, e.g. Documentation and Participate.

### PR DESCRIPTION
**Pull request by pedro-w**
Previously, the responsive layout was causing the left navigation area to overlap the main content for wider page sizes.

Fixes #96

### CODE REVIEW

**Comment by cgay** [comment]
This works well for the History, Documentation, and Participate pages (on my macOS Chrome browser) but unfortunately it kind of destroys the home page. 

Screen Shot 2019-12-21 at 4 26 17 PM

I'll leave this running at http://50.116.53.62:8000/index.html for a while if anyone wants to try with different browsers.

**Comment by cgay** [comment]
Hang on... The *current* home page is actually both better and worse than with this change:

Better: there's enough space for the code examples so that their lines don't soft wrap.

Worse: the Getting Started stuff is invisible at the bottom.

I think with this change it would be perfect if it just used more of the window width.

(My God, why are modern web pages so finicky? I feel like "just use tables" generally worked pretty well.)

**Comment by pedro-w** [comment]
More work neededm, I agree! With the change the layout is more consistent when you stretch it out, previously some elements just disappeared off the bottom. 

I feel that the code examples and the grey box ("Dylan is ...") should share the top row, then News, Getting Started and Learning About below. When the width is restricted these will stack up vertically instead of being side-by-side. What do you think?

But I don't know why it makes such poor used of the available width when stretched on a desktop monitor

**Comment by pedro-w** [comment]
At the moment the layout is one row with two columns taking up 2/3 and 1/3 of the width respectively. Column 1 has the code examples and News stacked vertically, and column 2 has the grey box, Getting Started and Learn About stacked vertically. When the width is restricted, all of column 1 sits above all of column 2.

**Comment by pedro-w** [comment]
Got it to look like this, what do you think? Unfortunately still goes a bit awry on narrow screens, so not ready yet.
screenshot

**Comment by cgay** [comment]
That layout looks reasonable to me.

**Pull request closed without merging**
